import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FeedbackPLZ from "./feedbackPlease.jsx";
import ClientAuthWrapper from '../components/ClientAuthWrapper.jsx'; // Import the wrapper instead

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Technicle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          margin: 0,
        }}
      >
        <ClientAuthWrapper>
          <div style={{ flex: 1 }}>{children}</div>
          <FeedbackPLZ />
        </ClientAuthWrapper>
      </body>
    </html>
  );
}